create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  admin_code text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  school text not null,
  name text not null,
  created_at timestamptz not null default now(),
  unique (class_id, school, name)
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  participant_id bigint not null references public.participants(id) on delete cascade,
  step smallint not null check (step between 1 and 4),
  status text not null default 'draft' check (status in ('draft', 'submitted')),
  data_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (participant_id, step)
);

alter table public.classes enable row level security;
alter table public.participants enable row level security;
alter table public.submissions enable row level security;

revoke all on public.classes from anon, authenticated;
revoke all on public.participants from anon, authenticated;
revoke all on public.submissions from anon, authenticated;

insert into public.classes (name, code, admin_code)
values ('AI 원데이 클래스', 'AI-ONEDAY', '260725')
on conflict (code) do update
set name = excluded.name;
